services:
  - type: web
    name: jankenwars
    runtime: node
    buildCommand: npm install && npx vite build && npx tsc && ls -la dist
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production