services:
  - type: web
    name: jankenwars
    runtime: node
    buildCommand: npm install && npx vite build && echo "Build completed successfully"
    startCommand: npx tsx server/index.ts
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production